/* =========================================================
   BHARATI STATION DIGITAL TWIN — DATA DEFINITIONS
========================================================= */

export const GROUND_ROOMS = [
  {
    id: "earth-lab",
    name: "Earth Sciences Lab",
    category: "Geology & Seismology",
    type: "lab",
    floor: "Ground Floor",
    floorId: "ground",
    x: -7.5,
    z: -3.0,
    w: 5.6,
    d: 4.2,
    floorType: "lab",
    powerKw: "14.2 kW",
    temp: "19.5 °C",
    status: "ONLINE",
    occupancy: "2 Scientists",
    classification: "RESEARCH AREA",
  },
  {
    id: "life-lab",
    name: "Life Sciences Lab",
    category: "Biology & Marine",
    type: "lab",
    floor: "Ground Floor",
    floorId: "ground",
    x: -1.8,
    z: -3.0,
    w: 5.2,
    d: 4.2,
    floorType: "lab",
    powerKw: "18.6 kW",
    temp: "20.2 °C",
    status: "ONLINE",
    occupancy: "3 Researchers",
    classification: "CLEAN LAB",
  },
  {
    id: "chem-lab",
    name: "Chemical & Atmospheric Lab",
    category: "Environmental Chemistry",
    type: "lab",
    floor: "Ground Floor",
    floorId: "ground",
    x: 3.8,
    z: -3.0,
    w: 5.4,
    d: 4.2,
    floorType: "lab",
    powerKw: "22.4 kW",
    temp: "18.8 °C",
    status: "ONLINE",
    occupancy: "2 Chemists",
    classification: "HAZMAT LEVEL 2",
  },
  {
    id: "elec-lab",
    name: "Electronics & Sensor Lab",
    category: "Instrumentation",
    type: "lab",
    floor: "Ground Floor",
    floorId: "ground",
    x: 9.2,
    z: -3.0,
    w: 4.8,
    d: 4.2,
    floorType: "lab",
    powerKw: "12.8 kW",
    temp: "21.0 °C",
    status: "ONLINE",
    occupancy: "1 Engineer",
    classification: "CALIBRATION LAB",
  },
  {
    id: "workshop",
    name: "Heavy Workshop & Maintenance",
    category: "Logistics & Repair",
    type: "workshop",
    floor: "Ground Floor",
    floorId: "ground",
    x: -7.5,
    z: 3.2,
    w: 5.6,
    d: 4.4,
    floorType: "steel",
    powerKw: "28.5 kW",
    temp: "16.0 °C",
    status: "ONLINE",
    occupancy: "2 Mechanics",
    classification: "INDUSTRIAL",
  },
  {
    id: "entrance-airlock",
    name: "Main Entry Airlock & Mudroom",
    category: "Access & Decontamination",
    type: "airlock",
    floor: "Ground Floor",
    floorId: "ground",
    x: -1.8,
    z: 3.2,
    w: 5.2,
    d: 4.4,
    floorType: "corridor",
    powerKw: "8.4 kW",
    temp: "14.5 °C",
    status: "ONLINE",
    occupancy: "Transient",
    classification: "SECURITY PERIMETER",
  },
  {
    id: "water-plant",
    name: "Water Treatment & Snow Melter",
    category: "Life Support Utility",
    type: "utility",
    floor: "Ground Floor",
    floorId: "ground",
    x: 3.8,
    z: 3.2,
    w: 5.4,
    d: 4.4,
    floorType: "steel",
    powerKw: "34.0 kW",
    temp: "18.0 °C",
    status: "ONLINE",
    occupancy: "Automated",
    classification: "CRITICAL UTILITY",
  },
  {
    id: "power-plant",
    name: "Power Generation & CHP Core",
    category: "Energy System",
    type: "power",
    floor: "Ground Floor",
    floorId: "ground",
    x: 9.2,
    z: 3.2,
    w: 4.8,
    d: 4.4,
    floorType: "steel",
    powerKw: "112.5 kW",
    temp: "24.5 °C",
    status: "ONLINE",
    occupancy: "Duty Engineer",
    classification: "HIGH VOLTAGE",
  },
];

export const FIRST_ROOMS = [
  {
    id: "control-room",
    name: "Control Room",
    category: "Operations & Mission Command",
    type: "operations",
    floor: "First Floor",
    floorId: "first",
    x: -7.5,
    z: -3.0,
    w: 5.6,
    d: 4.2,
    floorType: "lab",
    powerKw: "24.8 kW",
    temp: "21.5 °C",
    status: "ONLINE",
    occupancy: "Station Commander + 2 Ops",
    classification: "COMMAND CORE",
  },
  {
    id: "comms-room",
    name: "Communication Center",
    category: "Satellite & RF Comms",
    type: "comms",
    floor: "First Floor",
    floorId: "first",
    x: -1.8,
    z: -3.0,
    w: 5.2,
    d: 4.2,
    floorType: "lab",
    powerKw: "16.4 kW",
    temp: "20.8 °C",
    status: "ONLINE",
    occupancy: "1 Comms Officer",
    classification: "RESTRICTED",
  },
  {
    id: "berthing-ab",
    name: "Crew Cabins (A & B)",
    category: "Living Quarters",
    type: "living",
    floor: "First Floor",
    floorId: "first",
    x: 3.8,
    z: -3.0,
    w: 5.4,
    d: 4.2,
    floorType: "wood",
    powerKw: "4.2 kW",
    temp: "22.0 °C",
    status: "ONLINE",
    occupancy: "2 Personnel",
    classification: "HABITATION",
  },
  {
    id: "berthing-cd",
    name: "Crew Cabins (C & D)",
    category: "Living Quarters",
    type: "living",
    floor: "First Floor",
    floorId: "first",
    x: 9.2,
    z: -3.0,
    w: 4.8,
    d: 4.2,
    floorType: "wood",
    powerKw: "5.1 kW",
    temp: "21.8 °C",
    status: "ONLINE",
    occupancy: "4 Personnel",
    classification: "HABITATION",
  },
  {
    id: "medical-bay",
    name: "Medical Bay & Tele-ICU",
    category: "Healthcare & Emergency",
    type: "medical",
    floor: "First Floor",
    floorId: "first",
    x: -7.5,
    z: 3.2,
    w: 5.6,
    d: 4.4,
    floorType: "lab",
    powerKw: "11.2 kW",
    temp: "23.0 °C",
    status: "ONLINE",
    occupancy: "Station Medical Officer",
    classification: "MEDICAL PRIORITY",
  },
  {
    id: "galley-kitchen",
    name: "Galley & Pantry",
    category: "Food Prep & Dining",
    type: "kitchen",
    floor: "First Floor",
    floorId: "first",
    x: -1.8,
    z: 3.2,
    w: 5.2,
    d: 4.4,
    floorType: "steel",
    powerKw: "26.0 kW",
    temp: "20.5 °C",
    status: "ONLINE",
    occupancy: "Station Chef",
    classification: "FOOD SAFE",
  },
  {
    id: "dining-lounge",
    name: "Dining Hall & Crew Lounge",
    category: "Recreation & Community",
    type: "lounge",
    floor: "First Floor",
    floorId: "first",
    x: 3.8,
    z: 3.2,
    w: 5.4,
    d: 4.4,
    floorType: "living",
    powerKw: "9.8 kW",
    temp: "22.2 °C",
    status: "ONLINE",
    occupancy: "Common Gathering",
    classification: "COMMON AREA",
  },
  {
    id: "briefing-room",
    name: "Conference & Briefing",
    category: "Briefing & Planning",
    type: "operations",
    floor: "First Floor",
    floorId: "first",
    x: 9.2,
    z: 3.2,
    w: 4.8,
    d: 4.4,
    floorType: "wood",
    powerKw: "6.5 kW",
    temp: "21.0 °C",
    status: "ONLINE",
    occupancy: "Briefing Team",
    classification: "MEETING ROOM",
  },
];

export const SECOND_ROOMS = [
  {
    id: "met-observatory",
    name: "Meteorological Observatory",
    category: "Weather & Climate",
    type: "observatory",
    floor: "Second Floor",
    floorId: "second",
    x: -5.5,
    z: -2.0,
    w: 6.2,
    d: 4.4,
    floorType: "lab",
    powerKw: "16.8 kW",
    temp: "20.5 °C",
    status: "ONLINE",
    occupancy: "2 Meteorologists",
    classification: "WEATHER OBSERVATION",
  },
  {
    id: "lidar-lab",
    name: "Atmospheric LIDAR Lab",
    category: "Laser & Ozone Sounding",
    type: "lab",
    floor: "Second Floor",
    floorId: "second",
    x: 2.2,
    z: -2.0,
    w: 6.8,
    d: 4.4,
    floorType: "lab",
    powerKw: "28.4 kW",
    temp: "19.0 °C",
    status: "ONLINE",
    occupancy: "1 Laser Physicist",
    classification: "OPTICAL HAZARD",
  },
  {
    id: "sat-processing",
    name: "Satellite Data Processing",
    category: "High-Throughput Compute",
    type: "compute",
    floor: "Second Floor",
    floorId: "second",
    x: -5.5,
    z: 2.8,
    w: 6.2,
    d: 4.0,
    floorType: "lab",
    powerKw: "32.0 kW",
    temp: "18.5 °C",
    status: "ONLINE",
    occupancy: "Data Analyst",
    classification: "DATA CENTER",
  },
  {
    id: "cupola-lounge",
    name: "Observation Cupola",
    category: "Sky & Aurora Viewing",
    type: "cupola",
    floor: "Second Floor",
    floorId: "second",
    x: 2.2,
    z: 2.8,
    w: 6.8,
    d: 4.0,
    floorType: "living",
    powerKw: "3.5 kW",
    temp: "21.5 °C",
    status: "ONLINE",
    occupancy: "Observation Deck",
    classification: "SKYLIGHT CUPOLA",
  },
];

export const EXTERIOR_ASSETS = [
  {
    id: "station-envelope",
    name: "Bharati Main Station Complex",
    category: "Main Architectural Structure",
    type: "station",
    floor: "Exterior View",
    floorId: "exterior",
    powerKw: "165 kW",
    temp: "-24.0 °C",
    status: "ONLINE",
    occupancy: "47 Personnel Capacity",
    classification: "PRIMARY FACILITY",
  },
  {
    id: "solar-array-ext",
    name: "Bifacial Solar Array 01",
    category: "Renewable Energy Asset",
    type: "solar",
    floor: "Exterior View",
    floorId: "exterior",
    powerKw: "24.5 kW",
    temp: "-24.0 °C",
    status: "ONLINE",
    occupancy: "Autonomous Tracking",
    classification: "POWER HARVESTING",
  },
  {
    id: "comms-tower-ext",
    name: "Deep Space & SatCom Mast",
    category: "Communication Network",
    type: "comms",
    floor: "Exterior View",
    floorId: "exterior",
    powerKw: "12.0 kW",
    temp: "-24.0 °C",
    status: "ONLINE",
    occupancy: "99.8% Uplink Health",
    classification: "SATELLITE LINK",
  },
  {
    id: "aux-power-ext",
    name: "Auxiliary Power Pod 01",
    category: "Backup Power Generation",
    type: "power",
    floor: "Exterior View",
    floorId: "exterior",
    powerKw: "45.0 kW",
    temp: "-12.0 °C",
    status: "ONLINE",
    occupancy: "Standby Auto-Start",
    classification: "EMERGENCY BACKUP",
  },
];

export function getRoomsForFloor(floor) {
  if (floor === "first") return FIRST_ROOMS;
  if (floor === "second") return SECOND_ROOMS;
  if (floor === "exterior") return EXTERIOR_ASSETS;
  return GROUND_ROOMS;
}
