import { boundary, fact } from "./evidence";

/* =========================================================
   BHARATI STATION DIGITAL TWIN — STATION MODEL

   Room geometry is an architectural interpretation. The dossier gives
   Bharati's gross area (~2,500 m²), its 134 × 20-ft ISO container
   structure and a room count of 24 — but it is SILENT on storeys, floor
   allocation, corridor layout, staircases and individual room sizes.
   The layout below is therefore ours; the FACTS attached to each room
   are not, and each carries its evidence class.

   Fabricated telemetry (powerKw / temp / status / occupancy) has been
   removed from every object. The station has no public live feed for any
   of it — that absence is the problem PS 26060 exists to solve, so the
   twin names each gap instead of inventing a number to fill it.
========================================================= */

const ATCM36 = "ATCM36 Joint Inspection (Russia–US), 2012";
const OMRC = "OMRC tender NCAOR/LH(20)/2013";
const BOF = "bof architekten / NCPOR Significant Achievements";
const AWS = "data.ncpor.res.in — Bharati AWS (IMD), verified first-hand";

export const GROUND_ROOMS = [
  {
    id: "science-lab",
    name: "Science Laboratory",
    category: "Research",
    type: "lab",
    floor: "Ground Floor",
    floorId: "ground",
    x: -7.5,
    z: -3.0,
    w: 5.6,
    d: 4.2,
    floorType: "lab",
    tier: 4,
    summary:
      "The dossier does not break down Bharati's internal laboratories. One generic volume stands in for them rather than four invented disciplines.",
    facts: [
      fact("Datasets catalogued", "63", "A", "NCPOR NPDC browse_by_location"),
      fact("Metadata records", "51", "A", "NPDC search, parameter=Bharati"),
      fact(
        "42-ISEA science party",
        "37 scientists from 19 organisations",
        "A",
        "MoES Annual Report",
      ),
      fact(
        "Instrument classes held",
        "AWS, synoptic, radiation, surface ozone, GPS, magnetometers, riometer, black carbon, NOx",
        "C",
        "NPDC gated tier — station attribution not stated",
      ),
    ],
  },
  {
    id: "waste-store",
    name: "Waste Store",
    category: "Compliance",
    type: "storage",
    floor: "Ground Floor",
    floorId: "ground",
    x: -1.8,
    z: -3.0,
    w: 5.2,
    d: 4.2,
    floorType: "steel",
    tier: 1,
    summary:
      "Where compliance becomes spatial. Every drum here is a record the Indian Antarctic Act compels the station to keep.",
    facts: [
      fact("Container unit", "200 L drums", "A", `${OMRC} §2.6`),
      fact(
        "Operational split",
        "Biodegradable / non-degradable, held for removal to the mainland",
        "A",
        `${OMRC} §2.6`,
      ),
      fact(
        "Statutory categories",
        "Six — sewage; other liquid incl. fuels; incinerable solids; other solids; radioactive; prescribed",
        "A",
        "Indian Antarctic Act 2022 s.34(2); IAEP Rules 2023 r.29",
      ),
      fact(
        "Inspection duty",
        "Hazardous containers inspected and documented weekly",
        "A",
        "Act s.37(2)(d)",
      ),
      fact(
        "Reporting window",
        "Removals and disposal locations filed within 30 days of each permit year",
        "A",
        "IAEP Rules 2023 r.38(2)",
      ),
      boundary(
        "Waste tonnage and manifests",
        "Legally compelled to exist, therefore not published",
      ),
    ],
  },
  {
    id: "wastewater-plant",
    name: "Wastewater & MBR Plant",
    category: "Life Support",
    type: "utility",
    floor: "Ground Floor",
    floorId: "ground",
    x: 3.8,
    z: -3.0,
    w: 5.4,
    d: 4.2,
    floorType: "steel",
    tier: 1,
    summary:
      "Four segregated streams into a membrane bioreactor. The only plant on station with a publicly documented failure mode.",
    facts: [
      fact(
        "Segregated streams",
        "Galley, grease, grey, black",
        "A",
        `${OMRC} §2.5–2.6`,
      ),
      fact("Process", "MBR with biodegradation", "A", `${OMRC} §2.6`),
      fact(
        "Greywater reuse",
        "Bath and laundry greywater recycled into toilets",
        "A",
        `${OMRC} §2.6`,
      ),
      fact("Staffing", "Two engineers", "A", ATCM36),
      fact(
        "Outfall",
        "Quilty Bay, 60 m downstream of the seawater intake",
        "A",
        `${OMRC} §2.5–2.6`,
      ),
      fact(
        "Statutory discharge limits",
        "BOD₅ ≤ 25, COD ≤ 125, TSS ≤ 35 mg/L, pH 6–9",
        "A",
        "IAEP Rules 2023 Schedule 3",
      ),
      fact(
        "Documented failure mode",
        "Meets standards except when influent overloading is observed",
        "A",
        "Tiwari et al. 2017",
      ),
      boundary("Flow, TMP and effluent quality telemetry", "No public feed"),
    ],
  },
  {
    id: "fuel-store",
    name: "Fuel Storage Room",
    category: "Energy",
    type: "storage",
    floor: "Ground Floor",
    floorId: "ground",
    x: 9.2,
    z: -3.0,
    w: 4.8,
    d: 4.2,
    floorType: "steel",
    tier: 2,
    summary:
      "One of only three rooms the maintenance contract names as having dedicated fire suppression — sited across the corridor from the CHP it feeds.",
    facts: [
      fact(
        "Fire suppression",
        "High-pressure water and liquid-nitrogen spray; class A/B/C and electrical",
        "A",
        `${OMRC} §2.7`,
      ),
      fact(
        "Protected rooms on station",
        "Kitchen, CHP room and fuel storage",
        "A",
        `${OMRC} §2.7`,
      ),
      fact("Fuel", "Jet A-1 — 0.810 kg/L, 35.06 MJ/L", "A-ext", "ExxonMobil / Chevron"),
      boundary("Tank levels and day-tank draw rate", "No public feed"),
    ],
  },
  {
    id: "workshop",
    name: "Heavy Workshop & Maintenance",
    category: "Logistics",
    type: "workshop",
    floor: "Ground Floor",
    floorId: "ground",
    x: -7.5,
    z: 3.2,
    w: 5.6,
    d: 4.4,
    floorType: "steel",
    tier: 2,
    summary:
      "Run under the Operation, Maintenance, Repair & Care contract. Fault tracking here is a ticketing system, not SCADA.",
    facts: [
      fact(
        "Maintenance regime",
        "OMRC contract, 3-year term extendable by 2",
        "A",
        "NIT AL-11019/1/2025",
      ),
      fact(
        "Crew",
        "4–6 engineers and technicians, 12–14 month tours, up to 60-day handover overlap",
        "A",
        `${OMRC} §3`,
      ),
      fact(
        "Trades on station",
        "Vehicle mechanic, vehicle electrician, station electrician, welder, carpenter, boiler operator, crane and excavator operators",
        "A",
        "46-ISEA recruitment",
      ),
      fact(
        "Emergency drills",
        "Search-and-rescue, firefighting and spill response every 15 days",
        "A",
        ATCM36,
      ),
      fact(
        "Fault log",
        "Bharati-TIMES — an NCPOR internal web app for life-support technical issues",
        "C",
        "NCPOR Significant Achievements — ticketing, not telemetry",
      ),
      boundary("Spare-part stock levels", "No quantities published anywhere"),
    ],
  },
  {
    id: "entrance-airlock",
    name: "Main Entry & Mudroom",
    category: "Access",
    type: "airlock",
    floor: "Ground Floor",
    floorId: "ground",
    x: -1.8,
    z: 3.2,
    w: 5.2,
    d: 4.4,
    floorType: "corridor",
    tier: 4,
    summary:
      "The dossier is silent on Bharati's entry arrangement. The geometry is an interpretation; only the rostered duty below is sourced.",
    facts: [
      fact(
        "Alarm rounds",
        "Round-the-clock security vigil, periodic rounds checking life-support alarms, smoke, fire, oil and water leaks",
        "A",
        "NCPOR AL-01 §7.1.5 — a rostered human duty, not an automated system",
      ),
    ],
  },
  {
    id: "ro-plant",
    name: "Seawater RO Plant",
    category: "Life Support",
    type: "utility",
    floor: "Ground Floor",
    floorId: "ground",
    x: 3.8,
    z: 3.2,
    w: 5.4,
    d: 4.4,
    floorType: "steel",
    tier: 1,
    summary:
      "Bharati desalinates seawater — it does not melt snow. Snow and lake melt is Maitri's method, 4,800 km away.",
    facts: [
      fact("Source", "Seawater from Quilty Bay at 12 m depth", "A", `${OMRC} §2.5`),
      fact("Intake line", "~300 m insulated pipeline", "A", `${OMRC} §2.5`),
      fact("Process", "Reverse osmosis", "A", `${OMRC} §2.5`),
      fact("Design output", "2,000 L/day", "A", `${OMRC} §2.5`),
      fact("Storage", "12,000 L", "A", ATCM36),
      fact(
        "Observed consumption",
        "1,000 L/day for 13 crew ≈ 77 L/person/day",
        "A",
        `${ATCM36} — a 2012 snapshot, not a series`,
      ),
      fact(
        "Membrane service life",
        "3–5 years in seawater; clean-in-place at 10–15% normalised flow deviation",
        "A-ext",
        "Industry standard — not measured at Bharati",
      ),
      boundary(
        "Tank level, flow and permeate conductivity",
        "ATCM36 confirms a monitoring system managed by one person; its data is not public",
      ),
    ],
  },
  {
    id: "chp-station",
    name: "CHP Power Station",
    category: "Energy",
    type: "power",
    floor: "Ground Floor",
    floorId: "ground",
    x: 9.2,
    z: 3.2,
    w: 4.8,
    d: 4.4,
    floorType: "steel",
    tier: 1,
    summary:
      "The best-evidenced room in the building. Three units, one running, one asleep, one on standby — rotated on a documented 200-hour rule.",
    facts: [
      fact(
        "Prime movers",
        "3 × 100 kW combined heat and power",
        "A",
        `${ATCM36} — NCPOR's own page states 100 kVA; the unit conflict is unresolved`,
      ),
      fact("Redundancy", "One running, one sleep, one standby", "A", ATCM36),
      fact("Rotation policy", "Every 200 hours", "A", ATCM36),
      fact("Backup genset", "75 kW", "A", `${OMRC} §2.3–2.4`),
      fact("Field gensets", "2 × 2 kW", "A", `${OMRC} §2.3–2.4`),
      fact("Max thermal demand", "~155 kW-thermal", "A", `${OMRC} §2.4`),
      fact(
        "Day tank",
        "Drawn automatically from the fuel farm over a ~300 m line",
        "A",
        `${OMRC} §2.3`,
      ),
      fact(
        "Fire suppression",
        "High-pressure water and liquid-nitrogen spray",
        "A",
        `${OMRC} §2.7`,
      ),
      fact(
        "Modelled station load",
        "96.0 kW at 47 occupants — L = 61.8 + 0.727 × population",
        "D",
        "Two-point fit through the ATCM36 Maitri figures — a hypothesis, not a measured law",
      ),
      fact(
        "Wet-stacking floor",
        "Below 30% rated load; recommended band 50–85%",
        "A-ext",
        "Caterpillar / NFPA 110 — not measured at Bharati",
      ),
      boundary(
        "Output kW, fuel rate, runtime hours, exhaust and coolant temperatures",
        "The 200-hour rule implies metering; none of it is published",
      ),
    ],
  },
];

export const FIRST_ROOMS = [
  {
    id: "control-room",
    name: "Control Room",
    category: "Operations",
    type: "operations",
    floor: "First Floor",
    floorId: "first",
    x: -7.5,
    z: -3.0,
    w: 5.6,
    d: 4.2,
    floorType: "lab",
    tier: 2,
    summary:
      "Bharati has no SCADA. Incidents travel through the station manager to NCAOR — a human chain, which is exactly what this platform would replace.",
    facts: [
      fact(
        "Incident chain",
        "All incidents reported to the station manager, who transmits to NCAOR",
        "A",
        ATCM36,
      ),
      fact(
        "Energy and water monitoring",
        "A detailed monitoring system managed by one person",
        "A",
        `${ATCM36} — existence confirmed, data not public`,
      ),
      fact(
        "Vehicle authorisation",
        "Vehicles used only with prior permission from the station Leader",
        "A",
        "NCPOR AL-02 §1",
      ),
      fact(
        "Heating is a baseload",
        "10,838 °C·days annual HDD at Maitri; seasonal swing only 1.91×",
        "D",
        "Computed from the NCPOR 1990–2010 archive — Maitri, not Bharati",
      ),
      boundary("Live station SCADA mimic", "No SCADA exists at Bharati"),
    ],
  },
  {
    id: "comms-room",
    name: "Communication Centre",
    category: "Connectivity",
    type: "comms",
    floor: "First Floor",
    floorId: "first",
    x: -1.8,
    z: -3.0,
    w: 5.2,
    d: 4.2,
    floorType: "lab",
    tier: 2,
    summary:
      "The satellite earth station is run by NRSC, not by the people who run life support. That split caused a five-day blackout in 2013.",
    facts: [
      fact(
        "Link inventory",
        "Iridium telephones and open port, HF radio, a modest internet connection",
        "A",
        `${ATCM36} — 2012 inventory`,
      ),
      fact(
        "Earth station",
        "C-band to NRSC Shadnagar, operated by separate NRSC personnel",
        "A",
        "NCPOR Significant Achievements; AL-02 §4.1",
      ),
      fact(
        "Documented outage",
        "7–12 Oct 2013, five days, administrative cause",
        "A",
        "ncpor.res.in/news/view/196",
      ),
      fact(
        "Personal call ration",
        "6 min/month summer, 20 min/month winter",
        "A",
        "39-ISEA §5.0",
      ),
      fact(
        "Reported throughput",
        "“Both stations have Wi-Fi from a 2 mbps line”",
        "A",
        "Frontline 2023, quoting an NCPOR Group Director — a quote, not a specification",
      ),
      fact("Demo link rate", "128 kbps", "S", "Explicitly a simulation parameter"),
      fact(
        "Committed VSAT capacity",
        "No tender, NIT, CPPP or GeM listing found",
        "C",
        "Bandwidth specification not publicly verified",
      ),
      boundary("Link uptime, utilisation and latency", "No figures at any date"),
    ],
  },
  {
    id: "berthing-ab",
    name: "Crew Cabins A & B",
    category: "Habitation",
    type: "living",
    floor: "First Floor",
    floorId: "first",
    x: 3.8,
    z: -3.0,
    w: 5.4,
    d: 4.2,
    floorType: "wood",
    tier: 3,
    summary:
      "Headcounts are public; who sleeps where is not. Capacity is shown at station level rather than invented per cabin.",
    facts: [
      fact("Station capacity", "47 in the main building, summer and winter", "A", ATCM36),
      fact("Emergency shelter", "A further 25 — 72 total", "A", ATCM36),
      fact("Wintering 2023", "24 at Bharati, of 49 across both stations", "A", "MoES AR 2023-24"),
      fact("First winter-over", "13 people, 2012", "A", ATCM36),
      boundary("Crew roster, names and room assignments", "Never to be rendered"),
    ],
  },
  {
    id: "berthing-cd",
    name: "Crew Cabins C & D",
    category: "Habitation",
    type: "living",
    floor: "First Floor",
    floorId: "first",
    x: 9.2,
    z: -3.0,
    w: 4.8,
    d: 4.2,
    floorType: "wood",
    tier: 3,
    summary:
      "Tours run 12–14 months. The dossier gives role structure but never individuals.",
    facts: [
      fact("Tour length", "Wintering ~12–14 months", "A", `${OMRC}; AL-01`),
      fact(
        "Access window",
        "Roughly November–March; about eight months with no scheduled transport",
        "A",
        "39-ISEA §4.0",
      ),
      boundary("Crew roster, names and room assignments", "Never to be rendered"),
    ],
  },
  {
    id: "medical-bay",
    name: "Medical Bay",
    category: "Life Support",
    type: "medical",
    floor: "First Floor",
    floorId: "first",
    x: -7.5,
    z: 3.2,
    w: 5.6,
    d: 4.4,
    floorType: "lab",
    tier: 3,
    summary:
      "Previously labelled a Tele-ICU. Nothing in the dossier evidences telemedicine at Bharati, so the claim is gone.",
    facts: [
      fact("Staffing", "Medical doctor and male nurse are confirmed station roles", "A", "46-ISEA recruitment"),
      fact("Doctor tour", "~14 months", "A", "46-ISEA recruitment"),
      fact(
        "Pre-deployment gate",
        "AIIMS medical board; psychological assessment for wintering members only",
        "A",
        "NCPOR AL-05",
      ),
      boundary("Medical consumables and stock", "Excluded from the ledger for lack of evidence"),
    ],
  },
  {
    id: "galley-kitchen",
    name: "Galley & Pantry",
    category: "Habitation",
    type: "kitchen",
    floor: "First Floor",
    floorId: "first",
    x: -1.8,
    z: 3.2,
    w: 5.2,
    d: 4.4,
    floorType: "steel",
    tier: 3,
    summary:
      "One of the three fire-suppressed rooms. NCPOR provides no housekeeping staff — the galley runs on a duty roster.",
    facts: [
      fact("Role", "Chef/cook is a contracted position", "A", "46-ISEA recruitment"),
      fact(
        "Duty roster",
        "NCPOR provides no housekeeping staff; daily chores are taken by expedition members",
        "A",
        "NCPOR AL-01 §7.1–7.1.5",
      ),
      fact("LPG", "10–14 kg gas bottles", "A", "Resource ledger §8"),
      fact("Reefer food on vessel", "30.0 MT", "A", "Vessel tender"),
      fact(
        "Fire suppression",
        "High-pressure water and liquid-nitrogen spray",
        "A",
        `${OMRC} §2.7`,
      ),
      fact(
        "Combustible and food waste",
        "~0.97 kg/person/day",
        "D",
        "Derived from Syowa (Japan), COMNAP 2006",
      ),
    ],
  },
  {
    id: "dining-lounge",
    name: "Dining Hall & Crew Lounge",
    category: "Habitation",
    type: "lounge",
    floor: "First Floor",
    floorId: "first",
    x: 3.8,
    z: 3.2,
    w: 5.4,
    d: 4.4,
    floorType: "living",
    tier: 4,
    summary:
      "The dossier is silent on Bharati's common spaces. The one sourced fact worth attaching here is how the station shares its labour.",
    facts: [
      fact(
        "Community labour",
        "Every member is rostered for cleaning and round-the-clock alarm rounds",
        "A",
        "NCPOR AL-01 §7.1",
      ),
    ],
  },
  {
    id: "briefing-room",
    name: "Conference & Briefing",
    category: "Operations",
    type: "operations",
    floor: "First Floor",
    floorId: "first",
    x: 9.2,
    z: 3.2,
    w: 4.8,
    d: 4.4,
    floorType: "wood",
    tier: 4,
    summary:
      "Architectural interpretation. The dossier does not describe Bharati's meeting spaces.",
    facts: [
      fact(
        "Expedition cadence",
        "One expedition a year, launched the last week of October; vessel returns Cape Town the first week of April",
        "A",
        "NCPOR AL-01",
      ),
      fact(
        "Cargo cut-off",
        "31 August — cargo arriving later is returned at the owner's cost",
        "A",
        "NCPOR AL-01 §4.2",
      ),
    ],
  },
];

export const SECOND_ROOMS = [
  {
    id: "met-observatory",
    name: "Meteorological Observatory",
    category: "Environment",
    type: "observatory",
    floor: "Second Floor",
    floorId: "second",
    x: -5.5,
    z: -2.0,
    w: 6.2,
    d: 4.4,
    floorType: "lab",
    tier: 1,
    live: true,
    summary:
      "The only room in the building that can carry live numbers. Everything else on this twin is documentation, not telemetry.",
    facts: [
      fact("Owner", "India Meteorological Department, served by NCPOR", "A", AWS),
      fact("Cadence", "1-minute, continuous, 2015–2026", "A", AWS),
      fact(
        "Variables",
        "Temperature °C, pressure mbar, wind speed kt, wind direction °, relative humidity %",
        "A",
        AWS,
      ),
      fact("Access", "Plain HTTP GET, no authentication, XLSX response", "A", AWS),
      fact(
        "Hard cap",
        "100,000 rows per call with no pagination — about 69–77 days",
        "A",
        `${AWS} — an architectural constraint, not a bug`,
      ),
      fact("Missing-data sentinel", "−999.0", "A", AWS),
      fact(
        "Barometer availability",
        "18.06% missing, against 0.68% for every other sensor",
        "A",
        `${AWS} — measured over 100,000 rows, Jan–Mar 2024`,
      ),
      fact(
        "Station outages",
        "75 discrete runs in 69 days; longest 6.6 hours",
        "A",
        `${AWS} — measured`,
      ),
      fact(
        "No visibility variable",
        "A USAP-style Condition I/II/III tier cannot honestly be computed for Bharati",
        "A",
        AWS,
      ),
      fact(
        "No WMO station id",
        "Bharati is absent from ISD and GHCN; Zhongshan and Progress ~8–10 km away are proxies, never Bharati",
        "A",
        "NOAA NCEI",
      ),
    ],
  },
  {
    id: "geophysics-bay",
    name: "Geophysics Instrument Bay",
    category: "Research",
    type: "lab",
    floor: "Second Floor",
    floorId: "second",
    x: 2.2,
    z: -2.0,
    w: 6.8,
    d: 4.4,
    floorType: "lab",
    tier: 4,
    summary:
      "Previously an “Atmospheric LIDAR Lab”. No source places a LIDAR at Bharati, so the room now holds only instrument classes NCPOR's data centre is known to carry.",
    facts: [
      fact(
        "Instrument classes",
        "16-channel riometer, fluxgate / induction-coil / proton-precession magnetometers, GEC, surface ozone, radiation, NOx, black carbon",
        "C",
        "NPDC gated tier — station attribution is not public",
      ),
    ],
  },
  {
    id: "earth-station",
    name: "Satellite Earth Station",
    category: "Connectivity",
    type: "comms",
    floor: "Second Floor",
    floorId: "second",
    x: -5.5,
    z: 2.8,
    w: 6.2,
    d: 4.0,
    floorType: "lab",
    tier: 2,
    summary:
      "Previously “Satellite Data Processing”, a 32 kW data centre with no source. The real facility here is a C-band earth station staffed by a different organisation.",
    facts: [
      fact(
        "Operator",
        "NRSC personnel — a different organisation from the station's life-support crew",
        "A",
        "NCPOR Significant Achievements; AL-02 §4.1",
      ),
      fact("Link", "C-band to NRSC Shadnagar", "A", "NCPOR Significant Achievements"),
      fact(
        "Station LAN",
        "Fibre-optic and wireless transponder LAN across labs, workshops, utility areas and living modules; IP-EPABX installed 2015-16",
        "A",
        "NCPOR Significant Achievements",
      ),
      boundary("Throughput, utilisation and latency", "No public figures at any date"),
    ],
  },
  {
    id: "cupola-lounge",
    name: "Observation Deck",
    category: "Habitation",
    type: "cupola",
    floor: "Second Floor",
    floorId: "second",
    x: 2.2,
    z: 2.8,
    w: 6.8,
    d: 4.0,
    floorType: "living",
    tier: 4,
    summary:
      "Architectural invention. No source describes a cupola or viewing deck at Bharati — it carries no data and no status.",
    facts: [],
  },
];

export const EXTERIOR_ASSETS = [
  {
    id: "station-envelope",
    name: "Bharati Main Station Complex",
    category: "Structure",
    type: "station",
    floor: "Exterior",
    floorId: "exterior",
    tier: 1,
    summary:
      "134 shipping containers, erected in 127 days, designed for −40 °C and a 200 mph gust.",
    facts: [
      fact("Primary structure", "134 × 20-ft ISO containers", "A", BOF),
      fact("Gross area", "~2,500 m²", "A", BOF),
      fact("Rooms", "24", "A", `${BOF} — the count is sourced; the list is not`),
      fact("Erection time", "127 days on site", "A", BOF),
      fact("Design temperature", "−40 °C", "A", BOF),
      fact("Wind design", "200 mph gust, ultimate limit state", "A", BOF),
      fact(
        "Wall and roof U-value",
        "0.135 W/m²K over a 170 mm panel",
        "A",
        "RIBAJ interview with Bof Architekten",
      ),
      fact(
        "Glazing",
        "Outer 0.5–0.8, inner 1.1–1.2 W/m²K; cavity trace-heated to 5–10 °C",
        "A",
        "RIBAJ interview with Bof Architekten",
      ),
      fact("Capacity", "47, plus 25 in emergency shelter — 72 total", "A", ATCM36),
      fact("Position", "69°24.25′S 76°11.42′E, Larsemann Hills", "A", "NCPOR dataset page"),
      fact("Offload distance", "~100 m from the station, against Maitri's 120 km convoy", "A", "Dossier §12"),
      fact(
        "Elevated hull on stilts",
        "Rendered as an architectural interpretation",
        "S",
        "The dossier attributes steel stilts to Maitri; it is silent on Bharati being elevated",
      ),
    ],
  },
  {
    id: "fuel-farm-ext",
    name: "Fuel Farm",
    category: "Energy",
    type: "fuel",
    floor: "Exterior",
    floorId: "exterior",
    tier: 1,
    summary:
      "Thirteen double-hulled tanktainers, 20 m from where the ship ties up and 300 m from the day tank they feed.",
    facts: [
      fact("Tanks", "13 tanktainers × 24,000 L", "A", `${OMRC} §2.3`),
      fact(
        "Stated capacity",
        "296 kL stated, 312 kL by arithmetic",
        "A",
        `${OMRC} §2.3, §2.8 — the discrepancy is inside the source document`,
      ),
      fact("Construction", "Double-hull stainless in a carbon-steel frame", "A", `${OMRC} §2.3`),
      fact("Siting", "20 m from the ship anchor point", "A", `${OMRC} §2.8`),
      fact("Pipeline to day tank", "~300 m, automatic draw", "A", `${OMRC} §2.3`),
      fact("Ship-to-shore hose run", "~500 m", "A", "Vessel tender NCPOR/14(102)/26 §13.8"),
      fact("Leak protection", "Leak-resistant pipelines with automatic shut-off", "A", `${OMRC} §2.8`),
      fact("Supervision", "Four supervisors responsible for fuel transfers", "A", ATCM36),
      fact(
        "2012 consumption",
        "~120 kL — a construction year, not a steady state",
        "A",
        `${ATCM36} — current steady-state consumption was not obtained`,
      ),
      boundary("Tank levels and daily burn", "Only annual totals exist"),
    ],
  },
  {
    id: "comms-mast-ext",
    name: "Earth Station & HF/Iridium Mast",
    category: "Connectivity",
    type: "comms",
    floor: "Exterior",
    floorId: "exterior",
    tier: 2,
    summary:
      "Renamed from “Deep Space & SatCom Mast”. There is no deep-space capability at Bharati, and no published uplink SLA.",
    facts: [
      fact("Earth station", "C-band to NRSC Shadnagar, NRSC-operated", "A", "AL-02 §4.1"),
      fact("Radio", "MF/HF-SSB and VHF, GMDSS-certified operator", "A", "46-ISEA recruitment"),
      fact(
        "GEO geometry",
        "Horizon limit ±81.34°; Bharati at 69.4°S is usable but at a low elevation angle",
        "A-ext",
        "Orbital geometry",
      ),
      fact(
        "LEO constellations",
        "No evidence of Starlink or LEO procurement at either Indian station",
        "C",
        "A negative result, stated as a gap",
      ),
      boundary("Uplink health and availability", "Link statistics: no evidence found"),
    ],
  },
  {
    id: "aux-power-ext",
    name: "Backup Generator",
    category: "Energy",
    type: "power",
    floor: "Exterior",
    floorId: "exterior",
    tier: 2,
    summary:
      "Previously listed at 45 kW with automatic start. The documented rating is 75 kW, and nothing evidences auto-start.",
    facts: [
      fact("Rating", "75 kW", "A", `${OMRC} §2.3–2.4`),
      fact("Field gensets", "2 × 2 kW", "A", `${OMRC} §2.3–2.4`),
      boundary("Start mode, runtime and load", "No public feed; comparable stations run manual control"),
    ],
  },
];

export function getRoomsForFloor(floor) {
  if (floor === "first") return FIRST_ROOMS;
  if (floor === "second") return SECOND_ROOMS;
  if (floor === "exterior") return EXTERIOR_ASSETS;
  return GROUND_ROOMS;
}
